### ISSUE TITLE
Got some fatal error for badgeos-community-add-on

### ISSUE THREAD

**Issue by wayyeh** [opencredit/badgeos#622]
### Steps to Reproduce

1. install badgeos and community addon

**Actual result:**

`Fatal error: Uncaught Error: [] operator not supported for strings in /Applications/AMPPS/www/gauge/wp-content/plugins/badgeos-community-add-on/includes/bp-members.php:222 Stack trace: #0 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(286): BadgeOS_Community_Members->setup_nav(Array) #1 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /Applications/AMPPS/www/gauge/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /Applications/AMPPS/www/gauge/wp-content/plugins/buddypress/bp-core/bp-core-dependency.php(123): do_action('bp_setup_nav') #4 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(286): bp_setup_nav('') #5 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /Applications/AMPPS/www/gauge/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /Applications/AMPPS/www/gauge/wp-content/plugins/buddypress/bp-core/bp-core-dependency.php(235): do_action('bp_init') #8 /Applications/AMP in /Applications/AMPPS/www/gauge/wp-content/plugins/badgeos-community-add-on/includes/bp-members.php on line 222`

**Expected result:**

### Product Versions

- BadgeOS: 1.4.11
- badgeos-community-add-on 1.2.3
- WordPress: 4.9.4

### Additional Information

N/A

**Comment by hertachr** [comment]
same here
